version: "3"

volumes:
      produtosmvc:

networks:
        frontend:
        backend:

services:

      mysql:
        image: "mysql:8.0"
        volumes:
          - produtosmvc:/var/lib/mysql
          - ./projetoMVC/MVC2/_MySQL_Init_Script:/docker-entrypoint-initdb.d
        networks:
          - backend
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - bind-address=0.0.0.0
      
      mvc:
        build:
          context: ./projetoMVC/MVC2 .
          dockerfile: Dockerfile.dev
        networks:
          - backend
          - frontend
        ports:
          - 5000:80
        environment:
          - DBHOST=mysql
        depends_on:
          - mysql