#Estagio1 - base

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN mkdir /app
WORKDIR /app
EXPOSE 80/tcp

#Estagio2 - publish

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS publish
WORKDIR /app
COPY MVC2.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#Estagio3 - final

FROM base AS final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT [ "dotnet","MVC2.dll" ]
